target:
    host: localhost
    port: 8080
    path: v3/retrieveByHotelId

rate:
    rrate: 1
    rtype: s

verbose: true
templatefile: pdt.txt
datafile: pd.txt
verb: POST
regex: HotelId
headers:
    Content-Type: [application/x-www-form-urlencoded]
